// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vibecoding} from '../models';

export function Abort(arg1:string):Promise<void>;

export function CreateSession():Promise<string>;

export function GetConfig():Promise<vibecoding.SessionConfig>;

export function GetModels(arg1:string):Promise<Array<Record<string, any>>>;

export function GetProviders():Promise<Array<Record<string, string>>>;

export function GetSettings():Promise<vibecoding.VibeCodingSettings>;

export function Greet(arg1:string):Promise<string>;

export function LoadSessionConfig():Promise<Array<Record<string, any>>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RestoreSession(arg1:string):Promise<string>;

export function SaveSessionConfig(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveSettings(arg1:vibecoding.VibeCodingSettings):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendPermissionResponse(arg1:string,arg2:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function UpdateConfig(arg1:vibecoding.SessionConfig):Promise<void>;
